### ISSUE TITLE
Support basic commands like cp and sh

### ISSUE THREAD

**Issue by kosprov** [tarampampam/curl-docker#18]
In a Kubernetes environment, one handy way to use of `tarampampam/curl` is to boot it as an init container and copy the binary to another container that doesn't have `curl`. 

```
spec:
  containers:
    - image: a-thrid-party-image-without-curl
      volumeMounts:
        - name: static-curl
          mountPath: /usr/local/bin/curl
          subPath: curl
  initContainers:
    - image: tarampampam/curl
      command: [cp, /bin/curl, /export/curl]
      volumeMounts:
        - name: static-curl
          mountPath: /export
  volumes:
    - name: static-curl
      emptyDir: {}
```

but, being `scratch`-based, the image doesn't have `cp` and other basic commands.

It would be great if it was `busybox`-based or there were tag variants for that (e.g. `:busybox`, `:7.86.0-busybox`, etc).
